# Generated by Django 2.1.5 on 2022-02-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moovie', '0002_auto_20220218_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
