# Generated by Django 2.1.5 on 2022-02-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moovie', '0004_auto_20220218_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='media/movie_images/movie_placeholder.png', upload_to='movie_images'),
        ),
    ]
