# Generated by Django 2.1.5 on 2022-02-19 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moovie', '0006_auto_20220219_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movie_images/placeholder.png', upload_to='movie_images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='movietowatch',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default='person_images/placeholder.jpg', upload_to='person_images'),
        ),
        migrations.AlterField(
            model_name='review',
            name='header',
            field=models.TextField(max_length=128),
        ),
    ]
