# Generated by Django 2.1.5 on 2022-03-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moovie', '0007_auto_20220219_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='poster_images/placeholder.png', upload_to='poster_images'),
        ),
    ]
